[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "loop-point-finder"
version = "0.1.0"
description = "Find the loop point in the video."

requires-python = ">= 3.10"
dependencies = [
  "numpy",
  "opencv-python",
]

